In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/Usuariosyconsumodeelectricidadpormunicipio_clean.csv", dtype={
    'Cve_Edo': 'string',
    'Cve_Inegi': 'string',
    'Cve_Mun': 'string',
    'Estado': 'string',
    'Municipio': 'string',
    'Tarifa': 'string',
    'Periodo': 'int64',
    'Usuarios': 'int64',
    'Consumo': 'float64',
    'ISO': 'string'
})
df.head()

,Cve_Edo,Cve_Inegi,Cve_Mun,Estado,Municipio,Tarifa,Periodo,Usuarios,Consumo,ISO
0,1,01,001,Aguascalientes,Aguascalientes,01,2010,231727,281228528.0,MX-AGU
1,1,01,001,Aguascalientes,Aguascalientes,1A,2010,0,0.0,MX-AGU
2,1,01,001,Aguascalientes,Aguascalientes,1B,2010,0,0.0,MX-AGU
3,1,01,001,Aguascalientes,Aguascalientes,1C,2010,0,0.0,MX-AGU
4,1,01,001,Aguascalientes,Aguascalientes,1D,2010,0,0.0,MX-AGU

In [3]:
df[["Usuarios", "Consumo"]].describe()

           Usuarios       Consumo
count  8.971200e+05  8.971200e+05
mean   2.051234e+03  1.119125e+07
std    1.332090e+05  6.758325e+08
min   -1.700000e+01 -1.052949e+09
25%    0.000000e+00  0.000000e+00
50%    0.000000e+00  0.000000e+00
75%    0.000000e+00  0.000000e+00
max    4.220595e+07  2.180723e+11

In [4]:
df[["Estado", "Consumo", "Usuarios"]].groupby(by="Estado").sum().sort_values(by='Consumo', ascending=False)

                                      Consumo   Usuarios
Estado
Nacional                         3.307586e+12  609258186
Mexico                           5.631577e+11  134073536
Nuevo Leon                       5.548400e+11   55287204
Chihuahua                        5.370157e+11   57087210
Jalisco                          3.996560e+11   85303300
Distrito Federal                 3.883718e+11   88378116
Guanajuato                       3.499940e+11   59148616
Veracruz de Ignacio de la Llave  3.428994e+11   82170920
Sonora                           3.292191e+11   31652728
Coahuila de Zaragoza             3.270102e+11   29640720
Baja California                  3.137774e+11   37623284
Tamaulipas                       2.810454e+11   39098036
Puebla                           2.403919e+11   61160348
Michoacan de Ocampo              2.285810e+11   53149256
Sinaloa                          2.002156e+11   31817152
San Luis Potosi                  1.820121e+11   27961472
Queretaro                        1.512764e+11   21582928
Quintana Roo                     1.344715e+11   18106888
Hidalgo                          1.174677e+11   28363048
Tabasco                          1.057492e+11   22562344
Yucatan                          1.051453e+11   23333444
Durango                          9.659212e+10   16462892
Chiapas                          9.280883e+10   45507356
Guerrero                         9.113212e+10   33258964
Zacatecas                        8.551864e+10   18210772
Morelos                          8.294475e+10   22324424
Aguascalientes                   8.190769e+10   13785512
Oaxaca                           8.182821e+10   41881920
Baja California Sur              6.754928e+10    8358664
Tlaxcala                         5.827195e+10   11802980
Colima                           5.519257e+10    8987114
Nayarit                          4.579688e+10   13847956
Campeche                         4.046586e+10    9015436

In [5]:
df[["Estado", "Periodo", "Consumo", "Usuarios"]]\
.groupby(by=["Estado", "Periodo"]).sum().sort_values(by=["Estado", "Periodo"], ascending=True)

                             Consumo  Usuarios
Estado         Periodo
Aguascalientes 2010     8.825646e+09   1558096
               2011     9.680639e+09   1597028
               2012     9.873836e+09   1653044
               2013     9.714096e+09   1693280
               2014     1.051423e+10   1738564
...                              ...       ...
Zacatecas      2013     1.138309e+10   2242848
               2014     1.157558e+10   2293200
               2015     9.860541e+09   2351432
               2016     9.034581e+09   2415388
               2017     9.060940e+09   2481188

[264 rows x 2 columns]

In [6]:
df[["Estado", "Municipio", "Consumo", "Usuarios"]].loc[df["Estado"] == "Nuevo Leon"]\
.groupby(by=["Estado", "Municipio"]).sum().sort_values(by='Consumo', ascending=False)

                                          Consumo  Usuarios
Estado     Municipio
Nuevo Leon Total Estatal             2.774200e+11  27643602
           Monterrey                 5.982808e+10   6147424
           Apodaca                   4.356235e+10   3039066
           San Nicolas de los Garza  3.845293e+10   2241082
           Guadalupe                 2.918177e+10   3504844
           Gral. Escobedo            1.749378e+10   1961622
           Santa Catarina            1.564793e+10   1344254
           San Pedro Garza Garcia    1.427972e+10    703318
           Cadereyta Jimenez         1.095473e+10    719716
           Garcia                    6.118377e+09   1362648
           Cienega de Flores         5.860509e+09    261926
           Paras                     5.216039e+09     13312
           Juarez                    4.354401e+09   1676878
           Linares                   3.390215e+09    509846
           Carmen                    3.237884e+09    223124
           Montemorelos              2.877333e+09    484300
           Salinas Victoria          1.753556e+09    313906
           Pesqueria                 1.716362e+09    352740
           Santiago                  1.713127e+09    387348
           China                     1.654692e+09     84962
           Sabinas Hidalgo           1.601400e+09    266354
           Gral. Zuazua              1.583976e+09    317648
           Allende                   1.132381e+09    260876
           Galeana                   1.043745e+09    173884
           Anahuac                   6.336464e+08    109862
           Gral. Teran               5.280721e+08    110056
           Cerralvo                  4.601083e+08     66928
           Hidalgo                   3.738330e+08     99288
           Mina                      3.535458e+08     31476
           Dr. Arroyo                3.028012e+08    159146
           Aramberri                 2.695527e+08     63916
           Gral. Bravo               2.203066e+08     48922
           Los Ramones               1.925307e+08     72048
           Vallecillo                1.511485e+08     26462
           Lampazos de Naranjo       1.472714e+08     43220
           Agualeguas                1.263592e+08     45018
           Villaldama                1.176471e+08     42850
           Marin                     1.164610e+08     38642
           Bustamante                1.041120e+08     40996
           Abasolo                   1.037454e+08     14256
           Dr. Gonzalez              8.026645e+07     30394
           Hualahuises               7.273630e+07     36836
           Los Herreras              6.926189e+07     30950
           Mier y Noriega            6.563426e+07     28652
           Los Aldamas               5.929611e+07     22396
           Dr. Coss                  4.643913e+07     22702
           Gral. Trevino             3.976258e+07     18286
           Higueras                  3.369702e+07     13496
           Rayones                   2.479141e+07     19478
           Melchor Ocampo            2.461831e+07     12714
           Iturbide                  2.366635e+07     19164
           Gral. Zaragoza            2.340221e+07     24370