In [6]:
import pandas as pd

In [7]:
df = pd.read_csv("data/Usuariosyconsumodeelectricidadpormunicipio_clean.csv", dtype={
    'Cve Edo': 'string',
    'Cve Inegi': 'string',
    'Cve Mun': 'string',
    'Entidad Federativa': 'string',
    'Municipio': 'string',
    'Tarifa': 'string',
    'Periodo': 'int64',
    'Consumo': 'float64'
})
df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Consumo
0,1,01,001,Aguascalientes,Aguascalientes,01,2010,231727.0
1,1,01,001,Aguascalientes,Aguascalientes,1A,2010,0.0
2,1,01,001,Aguascalientes,Aguascalientes,1B,2010,0.0
3,1,01,001,Aguascalientes,Aguascalientes,1C,2010,0.0
4,1,01,001,Aguascalientes,Aguascalientes,1D,2010,0.0

In [8]:
df[["Consumo"]].describe()

            Consumo
count  1.794240e+06
mean   5.596650e+06
std    4.779184e+08
min   -1.052949e+09
25%    0.000000e+00
50%    0.000000e+00
75%    0.000000e+00
max    2.180723e+11

In [11]:
df[["Entidad Federativa", "Consumo"]].groupby(by="Entidad Federativa").sum().sort_values(by='Consumo', ascending=False)

                                      Consumo
Entidad Federativa
Nacional                         3.308195e+12
Mexico                           5.632918e+11
Nuevo Leon                       5.548953e+11
Chihuahua                        5.370728e+11
Jalisco                          3.997413e+11
Distrito Federal                 3.884602e+11
Guanajuato                       3.500531e+11
Veracruz de Ignacio de la Llave  3.429815e+11
Sonora                           3.292508e+11
Coahuila de Zaragoza             3.270399e+11
Baja California                  3.138151e+11
Tamaulipas                       2.810845e+11
Puebla                           2.404530e+11
Michoacan de Ocampo              2.286342e+11
Sinaloa                          2.002474e+11
San Luis Potosi                  1.820401e+11
Queretaro                        1.512980e+11
Quintana Roo                     1.344896e+11
Hidalgo                          1.174961e+11
Tabasco                          1.057718e+11
Yucatan                          1.051686e+11
Durango                          9.660858e+10
Chiapas                          9.285434e+10
Guerrero                         9.116538e+10
Zacatecas                        8.553686e+10
Morelos                          8.296707e+10
Aguascalientes                   8.192147e+10
Oaxaca                           8.187009e+10
Baja California Sur              6.755764e+10
Tlaxcala                         5.828375e+10
Colima                           5.520156e+10
Nayarit                          4.581073e+10
Campeche                         4.047487e+10

In [12]:
df[["Entidad Federativa", "Periodo", "Consumo"]]\
.groupby(by=["Entidad Federativa", "Periodo"]).sum().sort_values(by=["Entidad Federativa", "Periodo"], ascending=True)

                                 Consumo
Entidad Federativa Periodo
Aguascalientes     2010     8.827204e+09
                   2011     9.682236e+09
                   2012     9.875489e+09
                   2013     9.715789e+09
                   2014     1.051597e+10
...                                  ...
Zacatecas          2013     1.138533e+10
                   2014     1.157787e+10
                   2015     9.862893e+09
                   2016     9.036997e+09
                   2017     9.063421e+09

[264 rows x 1 columns]

In [26]:
df[["Entidad Federativa", "Municipio", "Consumo"]].loc[df["Entidad Federativa"] == "Nuevo Leon"]\
.groupby(by=["Entidad Federativa", "Municipio"]).sum().sort_values(by='Consumo', ascending=False)

                                                  Consumo
Entidad Federativa Municipio
Nuevo Leon         Total Estatal             2.774476e+11
                   Monterrey                 5.983423e+10
                   Apodaca                   4.356539e+10
                   San Nicolas de los Garza  3.845517e+10
                   Guadalupe                 2.918527e+10
                   Gral. Escobedo            1.749574e+10
                   Santa Catarina            1.564928e+10
                   San Pedro Garza Garcia    1.428042e+10
                   Cadereyta Jimenez         1.095545e+10
                   Garcia                    6.119740e+09
                   Cienega de Flores         5.860771e+09
                   Paras                     5.216052e+09
                   Juarez                    4.356078e+09
                   Linares                   3.390725e+09
                   Carmen                    3.238107e+09
                   Montemorelos              2.877817e+09
                   Salinas Victoria          1.753869e+09
                   Pesqueria                 1.716715e+09
                   Santiago                  1.713514e+09
                   China                     1.654777e+09
                   Sabinas Hidalgo           1.601667e+09
                   Gral. Zuazua              1.584294e+09
                   Allende                   1.132642e+09
                   Galeana                   1.043919e+09
                   Anahuac                   6.337563e+08
                   Gral. Teran               5.281822e+08
                   Cerralvo                  4.601753e+08
                   Hidalgo                   3.739323e+08
                   Mina                      3.535773e+08
                   Dr. Arroyo                3.029603e+08
                   Aramberri                 2.696166e+08
                   Gral. Bravo               2.203556e+08
                   Los Ramones               1.926028e+08
                   Vallecillo                1.511750e+08
                   Lampazos de Naranjo       1.473146e+08
                   Agualeguas                1.264042e+08
                   Villaldama                1.176899e+08
                   Marin                     1.164996e+08
                   Bustamante                1.041530e+08
                   Abasolo                   1.037597e+08
                   Dr. Gonzalez              8.029684e+07
                   Hualahuises               7.277313e+07
                   Los Herreras              6.929284e+07
                   Mier y Noriega            6.566292e+07
                   Los Aldamas               5.931851e+07
                   Dr. Coss                  4.646183e+07
                   Gral. Trevino             3.978087e+07
                   Higueras                  3.371052e+07
                   Rayones                   2.481088e+07
                   Melchor Ocampo            2.463103e+07
                   Iturbide                  2.368551e+07
                   Gral. Zaragoza            2.342658e+07