In [1]:
import pandas as pd
import numpy as np

## Electrificacionrural.csv

In [2]:
df = pd.read_csv("data/Electrificacionrural.csv")
df

,COMISION FEDERAL DE ELECTRICIDAD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,Electrificación por entidad federativa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ESTADO,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,1er trimestre 2021,2do trimestre 2021,3er trimestre 2021,4to trimestre 2021,NaN
4,AGUASCALIENTES,99.16%,99.17%,99.18%,99.45%,99.63%,99.64%,99.68%,99.68%,99.71%,99.75%,99.87%,99.60%,99.60%,99.60%,99.60%,NaN
5,BAJA CALIFORNIA,97.98%,98.56%,98.94%,99.08%,99.24%,99.32%,99.33%,99.37%,99.42%,99.45%,99.46%,99.15%,99.15%,99.15%,99.15%,NaN
6,BAJA CALIFORNIA SUR,96.56%,97.16%,97.58%,97.75%,98.84%,98.95%,99.00%,99.09%,99.15%,99.29%,99.36%,98.81%,98.81%,98.83%,98.83%,NaN
7,CAMPECHE,96.62%,97.80%,97.87%,97.99%,98.34%,98.67%,98.72%,98.81%,98.88%,99.22%,99.30%,98.60%,98.60%,98.61%,98.83%,NaN
8,COAHUILA,99.43%,99.50%,99.53%,99.54%,99.63%,99.64%,99.64%,99.68%,99.70%,99.83%,99.84%,99.72%,99.72%,99.73%,99.75%,NaN
9,COLIMA,98.93%,98.93%,98.97%,98.97%,99.19%,99.38%,99.61%,99.72%,99.80%,99.83%,99.83%,99.40%,99.41%,99.41%,99.58%,NaN
10,CHIAPAS,95.10%,95.57%,95.72%,95.78%,96.04%,96.13%,96.19%,96.25%,96.64%,97.37%,97.48%,97.96%,97.97%,97.99%,98.12%,NaN
11,CHIHUAHUA,95.79%,96.04%,96.42%,96.58%,96.96%,97.05%,97.15%,97.16%,97.28%,97.51%,97.66%,98.25%,98.34%,98.35%,98.40%,NaN
12,CIUDAD DE MÉXICO,99.47%,99.47%,99.48%,99.49%,99.49%,99.49%,99.49%,99.49%,99.54%,99.88%,99.89%,99.93%,99.93%,99.93%,99.94%,NaN
13,DURANGO,95.64%,95.73%,96.12%,96.38%,96.82%,96.92%,97.02%,97.05%,97.19%,97.27%,97.39%,97.59%,97.64%,97.66%,97.76%,NaN
14,GUANAJUATO,98.50%,98.67%,98.81%,99.02%,99.15%,99.23%,99.27%,99.30%,99.37%,99.43%,99.45%,99.49%,99.49%,99.49%,99.50%,NaN
15,GUERRERO,94.54%,94.59%,95.21%,95.33%,95.95%,96.18%,96.20%,96.23%,97.09%,97.90%,98.15%,97.93%,97.96%,98.02%,98.06%,NaN
16,HIDALGO,96.85%,97.50%,97.86%,98.45%,98.90%,99.09%,99.14%,99.20%,99.21%,99.34%,99.37%,99.01%,99.02%,99.08%,99.21%,NaN
17,JALISCO,98.90%,99.00%,99.05%,99.10%,99.28%,99.30%,99.35%,99.39%,99.47%,99.50%,99.54%,99.01%,99.02%,99.06%,99.08%,NaN
18,MEXICO,98.79%,98.89%,98.98%,98.98%,99.01%,99.04%,99.05%,99.06%,99.08%,99.28%,99.37%,99.64%,99.65%,99.68%,99.70%,NaN
19,MICHOACAN,98.04%,98.10%,98.24%,98.37%,98.68%,98.90%,99.02%,99.09%,99.13%,99.15%,99.22%,99.37%,99.38%,99.41%,99.44%,NaN
20,MORELOS,98.67%,98.67%,98.74%,98.74%,98.87%,98.99%,99.01%,99.02%,99.21%,99.31%,99.54%,99.57%,99.58%,99.62%,99.68%,NaN
21,NAYARIT,96.04%,96.09%,96.89%,97.10%,97.66%,97.69%,97.78%,97.90%,98.04%,98.11%,98.45%,97.64%,97.65%,97.70%,97.84%,NaN
22,NUEVO LEON,98.52%,98.76%,98.80%,98.80%,98.88%,98.88%,98.89%,98.89%,98.92%,99.18%,99.85%,99.84%,99.84%,99.84%,99.89%,NaN
23,OAXACA,94.18%,94.64%,95.02%,95.25%,95.64%,95.98%,96.01%,96.22%,96.49%,96.93%,97.20%,97.58%,97.60%,97.72%,97.94%,NaN
24,PUEBLA,97.81%,98.14%,98.45%,98.90%,99.20%,99.41%,99.46%,99.51%,99.51%,99.54%,99.58%,99.21%,99.21%,99.26%,99.28%,NaN
25,QUERETARO,97.43%,97.53%,97.73%,98.04%,98.30%,98.45%,98.57%,98.57%,98.84%,98.92%,98.93%,99.39%,99.39%,99.39%,99.40%,NaN
26,QUINTANA ROO,95.16%,98.67%,98.97%,99.02%,99.29%,99.41%,99.43%,99.45%,99.52%,99.62%,99.67%,99.03%,99.03%,99.07%,99.09%,NaN
27,SAN LUIS POTOSI,95.47%,95.86%,96.18%,96.21%,96.52%,96.88%,97.20%,97.32%,97.55%,97.87%,97.98%,98.53%,98.57%,98.60%,99.03%,NaN
28,SINALOA,98.33%,98.42%,98.62%,98.77%,98.91%,99.01%,99.05%,99.10%,99.19%,99.23%,99.42%,99.37%,99.40%,99.44%,99.48%,NaN
29,SONORA,97.65%,97.79%,98.48%,98.58%,98.85%,98.97%,99.00%,99.15%,99.20%,99.26%,99.31%,98.94%,98.97%,99.01%,99.03%,NaN
30,TABASCO,98.31%,98.37%,98.43%,98.44%,98.52%,98.58%,98.59%,98.61%,99.31%,99.32%,99.34%,99.32%,99.32%,99.33%,99.38%,NaN
31,TAMAULIPAS,97.07%,97.11%,97.20%,97.22%,97.38%,97.43%,97.78%,97.93%,98.00%,98.40%,99.16%,99.43%,99.45%,99.45%,99.69%,NaN
32,TLAXCALA,98.81%,99.31%,99.35%,99.55%,99.57%,99.61%,99.64%,99.73%,99.73%,99.74%,99.77%,99.48%,99.48%,99.52%,99.54%,NaN
33,VERACRUZ,96.31%,96.68%,97.41%,97.49%,97.68%,97.78%,97.87%,97.98%,98.04%,98.16%,98.30%,98.64%,98.66%,98.67%,98.73%,NaN
34,YUCATAN,96.22%,98.77%,98.94%,99.07%,99.16%,99.35%,99.42%,99.45%,99.54%,99.62%,99.68%,99.03%,99.04%,99.07%,99.14%,NaN
35,ZACATECAS,98.36%,98.50%,98.54%,98.59%,98.73%,98.77%,98.78%,98.78%,98.79%,98.97%,99.04%,99.30%,99.31%,99.31%,99.31%,NaN
36,NACIONAL,97.60%,97.89%,98.11%,98.23%,98.43%,98.53%,98.58%,98.64%,98.75%,98.95%,99.08%,99.11%,99.12%,99.15%,99.21%,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df = df.drop([0, 1, 2, 37, 38, 39, 40, 41, 42]).drop(["Unnamed: 16"], axis=1)
df = df.reset_index().drop(["index"], axis=1)
df.head()

,COMISION FEDERAL DE ELECTRICIDAD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,ESTADO,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,1er trimestre 2021,2do trimestre 2021,3er trimestre 2021,4to trimestre 2021
1,AGUASCALIENTES,99.16%,99.17%,99.18%,99.45%,99.63%,99.64%,99.68%,99.68%,99.71%,99.75%,99.87%,99.60%,99.60%,99.60%,99.60%
2,BAJA CALIFORNIA,97.98%,98.56%,98.94%,99.08%,99.24%,99.32%,99.33%,99.37%,99.42%,99.45%,99.46%,99.15%,99.15%,99.15%,99.15%
3,BAJA CALIFORNIA SUR,96.56%,97.16%,97.58%,97.75%,98.84%,98.95%,99.00%,99.09%,99.15%,99.29%,99.36%,98.81%,98.81%,98.83%,98.83%
4,CAMPECHE,96.62%,97.80%,97.87%,97.99%,98.34%,98.67%,98.72%,98.81%,98.88%,99.22%,99.30%,98.60%,98.60%,98.61%,98.83%

In [4]:
estados_lista = df["COMISION FEDERAL DE ELECTRICIDAD"]
estados_lista = estados_lista.reset_index().drop([0]).reset_index().drop(["index", "level_0"], axis=1)
estados_lista.rename({"COMISION FEDERAL DE ELECTRICIDAD": 'ESTADO'}, axis=1, inplace=True)
estados_lista.head()

                ESTADO
0       AGUASCALIENTES
1      BAJA CALIFORNIA
2  BAJA CALIFORNIA SUR
3             CAMPECHE
4             COAHUILA

In [5]:
df = df.drop(["COMISION FEDERAL DE ELECTRICIDAD"], axis=1)
df = df.reset_index().drop(["index"], axis=1).set_axis(range(df.shape[1]), axis=1)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,1er trimestre 2021,2do trimestre 2021,3er trimestre 2021,4to trimestre 2021
1,99.16%,99.17%,99.18%,99.45%,99.63%,99.64%,99.68%,99.68%,99.71%,99.75%,99.87%,99.60%,99.60%,99.60%,99.60%
2,97.98%,98.56%,98.94%,99.08%,99.24%,99.32%,99.33%,99.37%,99.42%,99.45%,99.46%,99.15%,99.15%,99.15%,99.15%
3,96.56%,97.16%,97.58%,97.75%,98.84%,98.95%,99.00%,99.09%,99.15%,99.29%,99.36%,98.81%,98.81%,98.83%,98.83%
4,96.62%,97.80%,97.87%,97.99%,98.34%,98.67%,98.72%,98.81%,98.88%,99.22%,99.30%,98.60%,98.60%,98.61%,98.83%

In [6]:
periodos_lista = df.iloc[0]
periodos_lista.head()

0    2010
1    2011
2    2012
3    2013
4    2014
Name: 0, dtype: object

In [7]:
df = df.drop([0]).reset_index().drop(["index"], axis=1)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14
0,99.16%,99.17%,99.18%,99.45%,99.63%,99.64%,99.68%,99.68%,99.71%,99.75%,99.87%,99.60%,99.60%,99.60%,99.60%
1,97.98%,98.56%,98.94%,99.08%,99.24%,99.32%,99.33%,99.37%,99.42%,99.45%,99.46%,99.15%,99.15%,99.15%,99.15%
2,96.56%,97.16%,97.58%,97.75%,98.84%,98.95%,99.00%,99.09%,99.15%,99.29%,99.36%,98.81%,98.81%,98.83%,98.83%
3,96.62%,97.80%,97.87%,97.99%,98.34%,98.67%,98.72%,98.81%,98.88%,99.22%,99.30%,98.60%,98.60%,98.61%,98.83%
4,99.43%,99.50%,99.53%,99.54%,99.63%,99.64%,99.64%,99.68%,99.70%,99.83%,99.84%,99.72%,99.72%,99.73%,99.75%

In [9]:
dict_df = dict()
dict_df["estado"] = list()
dict_df["periodo"] = list()
dict_df["electrificacion"] = list()
for i in range(df.shape[0]):
    for j in range(df.shape[1]-4):
        dict_df["estado"].append(estados_lista["ESTADO"].iloc[i])
        dict_df["periodo"].append(periodos_lista.iloc[j])
        dict_df["electrificacion"].append(df.iloc[i][j])
    dict_df["estado"].append(estados_lista["ESTADO"].iloc[i])
    dict_df["periodo"].append("2021")
    dict_df["electrificacion"].append(df.iloc[i][df.shape[1]-1])

In [10]:
dict_df

{'estado': ['AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'AGUASCALIENTES',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'BAJA CALIFORNIA SUR',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'CAMPECHE',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COAHUILA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'COLIMA',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIAPAS',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CHIHUAHUA',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'CIUDAD DE MÉXICO ',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'DURANGO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUANAJUATO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'GUERRERO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'HIDALGO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'JALISCO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MEXICO',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MICHOACAN',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'MORELOS',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NAYARIT',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'NUEVO LEON',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'OAXACA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'PUEBLA',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUERETARO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'QUINTANA ROO',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SAN LUIS POTOSI',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SINALOA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'SONORA',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TABASCO',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TAMAULIPAS',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'TLAXCALA',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'VERACRUZ',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'YUCATAN',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'ZACATECAS',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL',
  'NACIONAL'],
 'periodo': ['2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021',
  '2010',
  '2011',
  '2012',
  '2013',
  '2014',
  '2015',
  '2016',
  '2017',
  '2018',
  '2019',
  '2020',
  '2021'],
 'electrificacion': ['99.16%',
  '99.17%',
  '99.18%',
  '99.45%',
  '99.63%',
  '99.64%',
  '99.68%',
  '99.68%',
  '99.71%',
  '99.75%',
  '99.87%',
  '99.60%',
  '97.98%',
  '98.56%',
  '98.94%',
  '99.08%',
  '99.24%',
  '99.32%',
  '99.33%',
  '99.37%',
  '99.42%',
  '99.45%',
  '99.46%',
  '99.15%',
  '96.56%',
  '97.16%',
  '97.58%',
  '97.75%',
  '98.84%',
  '98.95%',
  '99.00%',
  '99.09%',
  '99.15%',
  '99.29%',
  '99.36%',
  '98.83%',
  '96.62%',
  '97.80%',
  '97.87%',
  '97.99%',
  '98.34%',
  '98.67%',
  '98.72%',
  '98.81%',
  '98.88%',
  '99.22%',
  '99.30%',
  '98.83%',
  '99.43%',
  '99.50%',
  '99.53%',
  '99.54%',
  '99.63%',
  '99.64%',
  '99.64%',
  '99.68%',
  '99.70%',
  '99.83%',
  '99.84%',
  '99.75%',
  '98.93%',
  '98.93%',
  '98.97%',
  '98.97%',
  '99.19%',
  '99.38%',
  '99.61%',
  '99.72%',
  '99.80%',
  '99.83%',
  '99.83%',
  '99.58%',
  '95.10%',
  '95.57%',
  '95.72%',
  '95.78%',
  '96.04%',
  '96.13%',
  '96.19%',
  '96.25%',
  '96.64%',
  '97.37%',
  '97.48%',
  '98.12%',
  '95.79%',
  '96.04%',
  '96.42%',
  '96.58%',
  '96.96%',
  '97.05%',
  '97.15%',
  '97.16%',
  '97.28%',
  '97.51%',
  '97.66%',
  '98.40%',
  '99.47%',
  '99.47%',
  '99.48%',
  '99.49%',
  '99.49%',
  '99.49%',
  '99.49%',
  '99.49%',
  '99.54%',
  '99.88%',
  '99.89%',
  '99.94%',
  '95.64%',
  '95.73%',
  '96.12%',
  '96.38%',
  '96.82%',
  '96.92%',
  '97.02%',
  '97.05%',
  '97.19%',
  '97.27%',
  '97.39%',
  '97.76%',
  '98.50%',
  '98.67%',
  '98.81%',
  '99.02%',
  '99.15%',
  '99.23%',
  '99.27%',
  '99.30%',
  '99.37%',
  '99.43%',
  '99.45%',
  '99.50%',
  '94.54%',
  '94.59%',
  '95.21%',
  '95.33%',
  '95.95%',
  '96.18%',
  '96.20%',
  '96.23%',
  '97.09%',
  '97.90%',
  '98.15%',
  '98.06%',
  '96.85%',
  '97.50%',
  '97.86%',
  '98.45%',
  '98.90%',
  '99.09%',
  '99.14%',
  '99.20%',
  '99.21%',
  '99.34%',
  '99.37%',
  '99.21%',
  '98.90%',
  '99.00%',
  '99.05%',
  '99.10%',
  '99.28%',
  '99.30%',
  '99.35%',
  '99.39%',
  '99.47%',
  '99.50%',
  '99.54%',
  '99.08%',
  '98.79%',
  '98.89%',
  '98.98%',
  '98.98%',
  '99.01%',
  '99.04%',
  '99.05%',
  '99.06%',
  '99.08%',
  '99.28%',
  '99.37%',
  '99.70%',
  '98.04%',
  '98.10%',
  '98.24%',
  '98.37%',
  '98.68%',
  '98.90%',
  '99.02%',
  '99.09%',
  '99.13%',
  '99.15%',
  '99.22%',
  '99.44%',
  '98.67%',
  '98.67%',
  '98.74%',
  '98.74%',
  '98.87%',
  '98.99%',
  '99.01%',
  '99.02%',
  '99.21%',
  '99.31%',
  '99.54%',
  '99.68%',
  '96.04%',
  '96.09%',
  '96.89%',
  '97.10%',
  '97.66%',
  '97.69%',
  '97.78%',
  '97.90%',
  '98.04%',
  '98.11%',
  '98.45%',
  '97.84%',
  '98.52%',
  '98.76%',
  '98.80%',
  '98.80%',
  '98.88%',
  '98.88%',
  '98.89%',
  '98.89%',
  '98.92%',
  '99.18%',
  '99.85%',
  '99.89%',
  '94.18%',
  '94.64%',
  '95.02%',
  '95.25%',
  '95.64%',
  '95.98%',
  '96.01%',
  '96.22%',
  '96.49%',
  '96.93%',
  '97.20%',
  '97.94%',
  '97.81%',
  '98.14%',
  '98.45%',
  '98.90%',
  '99.20%',
  '99.41%',
  '99.46%',
  '99.51%',
  '99.51%',
  '99.54%',
  '99.58%',
  '99.28%',
  '97.43%',
  '97.53%',
  '97.73%',
  '98.04%',
  '98.30%',
  '98.45%',
  '98.57%',
  '98.57%',
  '98.84%',
  '98.92%',
  '98.93%',
  '99.40%',
  '95.16%',
  '98.67%',
  '98.97%',
  '99.02%',
  '99.29%',
  '99.41%',
  '99.43%',
  '99.45%',
  '99.52%',
  '99.62%',
  '99.67%',
  '99.09%',
  '95.47%',
  '95.86%',
  '96.18%',
  '96.21%',
  '96.52%',
  '96.88%',
  '97.20%',
  '97.32%',
  '97.55%',
  '97.87%',
  '97.98%',
  '99.03%',
  '98.33%',
  '98.42%',
  '98.62%',
  '98.77%',
  '98.91%',
  '99.01%',
  '99.05%',
  '99.10%',
  '99.19%',
  '99.23%',
  '99.42%',
  '99.48%',
  '97.65%',
  '97.79%',
  '98.48%',
  '98.58%',
  '98.85%',
  '98.97%',
  '99.00%',
  '99.15%',
  '99.20%',
  '99.26%',
  '99.31%',
  '99.03%',
  '98.31%',
  '98.37%',
  '98.43%',
  '98.44%',
  '98.52%',
  '98.58%',
  '98.59%',
  '98.61%',
  '99.31%',
  '99.32%',
  '99.34%',
  '99.38%',
  '97.07%',
  '97.11%',
  '97.20%',
  '97.22%',
  '97.38%',
  '97.43%',
  '97.78%',
  '97.93%',
  '98.00%',
  '98.40%',
  '99.16%',
  '99.69%',
  '98.81%',
  '99.31%',
  '99.35%',
  '99.55%',
  '99.57%',
  '99.61%',
  '99.64%',
  '99.73%',
  '99.73%',
  '99.74%',
  '99.77%',
  '99.54%',
  '96.31%',
  '96.68%',
  '97.41%',
  '97.49%',
  '97.68%',
  '97.78%',
  '97.87%',
  '97.98%',
  '98.04%',
  '98.16%',
  '98.30%',
  '98.73%',
  '96.22%',
  '98.77%',
  '98.94%',
  '99.07%',
  '99.16%',
  '99.35%',
  '99.42%',
  '99.45%',
  '99.54%',
  '99.62%',
  '99.68%',
  '99.14%',
  '98.36%',
  '98.50%',
  '98.54%',
  '98.59%',
  '98.73%',
  '98.77%',
  '98.78%',
  '98.78%',
  '98.79%',
  '98.97%',
  '99.04%',
  '99.31%',
  '97.60%',
  '97.89%',
  '98.11%',
  '98.23%',
  '98.43%',
  '98.53%',
  '98.58%',
  '98.64%',
  '98.75%',
  '98.95%',
  '99.08%',
  '99.21%']}

In [11]:
clean_df = pd.DataFrame.from_dict(dict_df)
clean_df.head()

           estado periodo electrificacion
0  AGUASCALIENTES    2010          99.16%
1  AGUASCALIENTES    2011          99.17%
2  AGUASCALIENTES    2012          99.18%
3  AGUASCALIENTES    2013          99.45%
4  AGUASCALIENTES    2014          99.63%

In [12]:
clean_df.to_csv("data/Electrificacionrural_clean.csv", index=False)

## Usuariosyconsumodeelectricidadpormunicipio.csv

In [4]:
df = pd.read_csv("data/Usuariosyconsumodeelectricidadpormunicipio.csv")
df

C:\Users\saulp\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (1,2) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,COMISIÓN FEDERAL DE ELECTRICIDAD,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,NÚMERO DE USUARIOS POR MUNICIPIO 2010 A 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
2,1,01,001,Aguascalientes ...,Aguascalientes ...,01,"231,727","236,475","244,474","251,805","258,658","266,481","272,727","282,395"
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,0,0,0,0,0,0,5,3
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,0,0,0,0,0,0,65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224280,|,99,999,N a c i o n a l ...,Sector Electrico ...,GDMTH,0,0,0,0,0,0,0,"5,040,063,048"
224281,|,99,999,N a c i o n a l ...,Sector Electrico ...,GDMTO,0,0,0,0,0,0,0,"478,790,854"
224282,|,99,999,N a c i o n a l ...,Sector Electrico ...,DIST,0,0,0,0,0,0,0,"1,925,236,234"
224283,|,99,999,N a c i o n a l ...,Sector Electrico ...,DIT,0,0,0,0,0,0,0,"989,531,095"
224284,|,99,999,N a c i o n a l ...,Sector Electrico ...,TOTAL,"186,638,874,542","200,945,887,412","206,480,280,078","206,129,990,014","208,014,908,186","212,200,817,318","218,072,292,588","215,309,928,125"

In [5]:
df.columns = df.iloc[1]
df

1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
0,NÚMERO DE USUARIOS POR MUNICIPIO 2010 A 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
2,1,01,001,Aguascalientes ...,Aguascalientes ...,01,"231,727","236,475","244,474","251,805","258,658","266,481","272,727","282,395"
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,0,0,0,0,0,0,5,3
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,0,0,0,0,0,0,65,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224280,|,99,999,N a c i o n a l ...,Sector Electrico ...,GDMTH,0,0,0,0,0,0,0,"5,040,063,048"
224281,|,99,999,N a c i o n a l ...,Sector Electrico ...,GDMTO,0,0,0,0,0,0,0,"478,790,854"
224282,|,99,999,N a c i o n a l ...,Sector Electrico ...,DIST,0,0,0,0,0,0,0,"1,925,236,234"
224283,|,99,999,N a c i o n a l ...,Sector Electrico ...,DIT,0,0,0,0,0,0,0,"989,531,095"
224284,|,99,999,N a c i o n a l ...,Sector Electrico ...,TOTAL,"186,638,874,542","200,945,887,412","206,480,280,078","206,129,990,014","208,014,908,186","212,200,817,318","218,072,292,588","215,309,928,125"

In [6]:
m = df.index[df["Cve Edo"] == "CONSUMO 2010A  2017 UNIDAD EN (KW/H)"].tolist()[0]
m

112144

In [7]:
usuarios_df = df.loc[:m,:]
usuarios_df.head()

1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
0,NÚMERO DE USUARIOS POR MUNICIPIO 2010 A 2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
2,1,01,001,Aguascalientes ...,Aguascalientes ...,01,"231,727","236,475","244,474","251,805","258,658","266,481","272,727","282,395"
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,0,0,0,0,0,0,5,3
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,0,0,0,0,0,0,65,0

In [8]:
consumo_df = df.loc[m:,:]
consumo_df.head()

1,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,2010,2011,2012,2013,2014,2015,2016,2017
112144,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112145,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,01,"281,228,528","290,328,904","288,575,239","293,812,094","297,502,527","300,805,382","305,970,562","313,762,202"
112146,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1A,0,0,0,0,0,0,588,"1,911"
112147,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1B,0,0,0,0,0,1,"13,144","423,706"
112148,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1C,0,0,0,0,0,0,0,617

In [9]:
usuarios_df = usuarios_df.drop([0, 1])
usuarios_df = usuarios_df.reset_index().drop(["index"], axis=1)
usuarios_df.index.name = 'index'
usuarios_df = usuarios_df.melt(id_vars=list(usuarios_df.columns[:-8]), 
        var_name="Periodo", 
        value_name="Usuarios")
usuarios_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Usuarios
0,1,01,001,Aguascalientes ...,Aguascalientes ...,01,2010,"231,727"
1,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [10]:
consumo_df = consumo_df.drop([112144])
consumo_df = consumo_df.reset_index().drop(["index"], axis=1)
consumo_df.index.name = 'index'
consumo_df = consumo_df.melt(id_vars=list(consumo_df.columns[:-8]), 
        var_name="Periodo", 
        value_name="Consumo")
consumo_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Consumo
0,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,01,2010,"281,228,528"
1,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [11]:
df = df.drop([0, 1])
df = df.reset_index().drop(["index"], axis=1)
df.index.name = 'index'
df = df.melt(id_vars=list(df.columns[:-8]), 
        var_name="Periodo", 
        value_name="Cantidad")
df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Cantidad
0,1,01,001,Aguascalientes ...,Aguascalientes ...,01,2010,"231,727"
1,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [12]:
df.isna().sum()

Cve Edo                8
Cve Inegi             24
Cve Mun               24
Entidad Federativa    24
Municipio             24
Tarifa                24
Periodo                0
Cantidad              24
dtype: int64

In [13]:
df.loc[df["Cantidad"].isna()]

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Cantidad
112140,NaN,NaN,NaN,NaN,NaN,NaN,2010,NaN
112141,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2010,NaN
112142,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2010,NaN
336423,NaN,NaN,NaN,NaN,NaN,NaN,2011,NaN
336424,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2011,NaN
336425,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2011,NaN
560706,NaN,NaN,NaN,NaN,NaN,NaN,2012,NaN
560707,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2012,NaN
560708,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2012,NaN
784989,NaN,NaN,NaN,NaN,NaN,NaN,2013,NaN
784990,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2013,NaN
784991,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2013,NaN
1009272,NaN,NaN,NaN,NaN,NaN,NaN,2014,NaN
1009273,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2014,NaN
1009274,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2014,NaN
1233555,NaN,NaN,NaN,NaN,NaN,NaN,2015,NaN
1233556,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2015,NaN
1233557,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2015,NaN
1457838,NaN,NaN,NaN,NaN,NaN,NaN,2016,NaN
1457839,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2016,NaN
1457840,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2016,NaN
1682121,NaN,NaN,NaN,NaN,NaN,NaN,2017,NaN
1682122,COMISIÓN FEDERAL DE ELECTRICIDAD,NaN,NaN,NaN,NaN,NaN,2017,NaN
1682123,CONSUMO 2010A 2017 UNIDAD EN (KW/H),NaN,NaN,NaN,NaN,NaN,2017,NaN

In [14]:
df = df.dropna()
usuarios_df = usuarios_df.dropna()
consumo_df = consumo_df.dropna()

In [15]:
df.isna().sum()

Cve Edo               0
Cve Inegi             0
Cve Mun               0
Entidad Federativa    0
Municipio             0
Tarifa                0
Periodo               0
Cantidad              0
dtype: int64

In [16]:
df = df.reset_index().drop(["index"], axis=1)
df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Cantidad
0,1,01,001,Aguascalientes ...,Aguascalientes ...,01,2010,"231,727"
1,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [17]:
usuarios_df = usuarios_df.reset_index().drop(["index"], axis=1)
usuarios_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Usuarios
0,1,01,001,Aguascalientes ...,Aguascalientes ...,01,2010,"231,727"
1,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [18]:
consumo_df = consumo_df.reset_index().drop(["index"], axis=1)
consumo_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Consumo
0,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,01,2010,"281,228,528"
1,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1A,2010,0
2,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1B,2010,0
3,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1C,2010,0
4,1,1.0,1.0,Aguascalientes ...,Aguascalientes ...,1D,2010,0

In [19]:
usuarios_consumo_df = usuarios_df
usuarios_consumo_df["Consumo"] = consumo_df["Consumo"]
usuarios_consumo_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Usuarios,Consumo
0,1,01,001,Aguascalientes ...,Aguascalientes ...,01,2010,"231,727","281,228,528"
1,1,01,001,Aguascalientes ...,Aguascalientes ...,1A,2010,0,0
2,1,01,001,Aguascalientes ...,Aguascalientes ...,1B,2010,0,0
3,1,01,001,Aguascalientes ...,Aguascalientes ...,1C,2010,0,0
4,1,01,001,Aguascalientes ...,Aguascalientes ...,1D,2010,0,0

In [20]:
del df, usuarios_df, consumo_df

In [21]:
usuarios_consumo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 897120 entries, 0 to 897119
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Cve Edo             897120 non-null  object
 1   Cve Inegi           897120 non-null  object
 2   Cve Mun             897120 non-null  object
 3   Entidad Federativa  897120 non-null  object
 4   Municipio           897120 non-null  object
 5   Tarifa              897120 non-null  object
 6   Periodo             897120 non-null  object
 7   Usuarios            897120 non-null  object
 8   Consumo             897120 non-null  object
dtypes: object(9)
memory usage: 61.6+ MB

In [22]:
usuarios_consumo_df['Usuarios'] = usuarios_consumo_df['Usuarios'].replace(',','', regex=True)
usuarios_consumo_df['Usuarios'] = usuarios_consumo_df['Usuarios'].astype(float)

usuarios_consumo_df['Consumo'] = usuarios_consumo_df['Consumo'].replace(',','', regex=True)
usuarios_consumo_df['Consumo'] = usuarios_consumo_df['Consumo'].astype(float)

In [23]:
usuarios_consumo_df['Entidad Federativa'].unique()

array(['Aguascalientes                                    ',
       'Baja California                                   ',
       'Baja California Sur                               ',
       'Campeche                                          ',
       'Coahuila de Zaragoza                              ',
       'Colima                                            ',
       'Chiapas                                           ',
       'Chihuahua                                         ',
       'Distrito Federal                                  ',
       'Durango                                           ',
       'Guanajuato                                        ',
       'Guerrero                                          ',
       'Hidalgo                                           ',
       'Jalisco                                           ',
       'Mexico                                            ',
       'Michoacan de Ocampo                               ',
       'Morelos                                           ',
       'Nayarit                                           ',
       'Nuevo Leon                                        ',
       'Oaxaca                                            ',
       'Puebla                                            ',
       'Queretaro                                         ',
       'Quintana Roo                                      ',
       'San Luis Potosi                                   ',
       'Sinaloa                                           ',
       'Sonora                                            ',
       'Tabasco                                           ',
       'Tamaulipas                                        ',
       'Tlaxcala                                          ',
       'Veracruz de Ignacio de la Llave                   ',
       'Yucatan                                           ',
       'Zacatecas                                         ',
       'N a c i o n a l                                   '], dtype=object)

In [24]:
usuarios_consumo_df['Entidad Federativa'] = usuarios_consumo_df['Entidad Federativa'].str.strip()
usuarios_consumo_df['Entidad Federativa'] = usuarios_consumo_df['Entidad Federativa'].apply(lambda x: x if x != "N a c i o n a l" else x.replace(' ',''))
usuarios_consumo_df['Municipio'] = usuarios_consumo_df['Municipio'].str.strip()
usuarios_consumo_df['Cve Edo'] = usuarios_consumo_df['Cve Edo'].str.strip()
usuarios_consumo_df['Cve Inegi'] = usuarios_consumo_df['Cve Inegi'].str.strip()
usuarios_consumo_df['Tarifa'] = usuarios_consumo_df['Tarifa'].str.strip()

In [25]:
usuarios_consumo_df['Entidad Federativa'].unique()

array(['Aguascalientes', 'Baja California', 'Baja California Sur',
       'Campeche', 'Coahuila de Zaragoza', 'Colima', 'Chiapas',
       'Chihuahua', 'Distrito Federal', 'Durango', 'Guanajuato',
       'Guerrero', 'Hidalgo', 'Jalisco', 'Mexico', 'Michoacan de Ocampo',
       'Morelos', 'Nayarit', 'Nuevo Leon', 'Oaxaca', 'Puebla',
       'Queretaro', 'Quintana Roo', 'San Luis Potosi', 'Sinaloa',
       'Sonora', 'Tabasco', 'Tamaulipas', 'Tlaxcala',
       'Veracruz de Ignacio de la Llave', 'Yucatan', 'Zacatecas',
       'Nacional'], dtype=object)

In [26]:
usuarios_consumo_df.head()

,Cve Edo,Cve Inegi,Cve Mun,Entidad Federativa,Municipio,Tarifa,Periodo,Usuarios,Consumo
0,1,01,001,Aguascalientes,Aguascalientes,01,2010,231727.0,281228528.0
1,1,01,001,Aguascalientes,Aguascalientes,1A,2010,0.0,0.0
2,1,01,001,Aguascalientes,Aguascalientes,1B,2010,0.0,0.0
3,1,01,001,Aguascalientes,Aguascalientes,1C,2010,0.0,0.0
4,1,01,001,Aguascalientes,Aguascalientes,1D,2010,0.0,0.0

In [27]:
usuarios_consumo_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 897120 entries, 0 to 897119
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Cve Edo             897120 non-null  object
 1   Cve Inegi           524272 non-null  object
 2   Cve Mun             897120 non-null  object
 3   Entidad Federativa  897120 non-null  object
 4   Municipio           897120 non-null  object
 5   Tarifa              897120 non-null  object
 6   Periodo             897120 non-null  object
 7   Usuarios            897120 non-null  float64
 8   Consumo             897120 non-null  float64
dtypes: float64(2), object(7)
memory usage: 61.6+ MB

In [28]:
iso_code_dict = {
    "Aguascalientes": "AGU",
    "Baja California": "BCN",
    "Baja California Sur": "BCS",
    "Campeche": "CAM",
    "Coahuila de Zaragoza": "COA",
    "Colima": "COL",
    "Chiapas": "CHP",
    "Chihuahua": "CHH",
    "Distrito Federal": "-DF",
    "Durango": "DUR",
    "Guanajuato": "GUA",
    "Guerrero": "GRO",
    "Hidalgo": "HID",
    "Jalisco": "JAL",
    "Mexico": "MEX",
    "Michoacan de Ocampo": "MIC",
    "Morelos": "MOR",
    "Nayarit": "NAY",
    "Nuevo Leon": "NLE",
    "Oaxaca": "OAX",
    "Puebla": "PUE",
    "Queretaro": "QUE",
    "Quintana Roo": "ROO",
    "San Luis Potosi": "SLP",
    "Sinaloa": "SIN",
    "Sonora": "SON",
    "Tabasco": "TAB",
    "Tamaulipas": "TAM",
    "Tlaxcala": "TLA",
    "Veracruz de Ignacio de la Llave": "VER",
    "Yucatan": "YUC",
    "Zacatecas": "ZAC",
    "Nacional": "---"
}

In [29]:
usuarios_consumo_df['ISO'] = usuarios_consumo_df['Entidad Federativa']\
.apply(lambda x: "MX-" + iso_code_dict.get(x, ""))

In [30]:
usuarios_consumo_df = usuarios_consumo_df.rename(columns={"Entidad Federativa": "Estado", "Cve Mun": "Cve_Mun", 
                                                         "Cve Edo": "Cve_Edo", "Cve Inegi": "Cve_Inegi"})
usuarios_consumo_df.head()

,Cve_Edo,Cve_Inegi,Cve_Mun,Estado,Municipio,Tarifa,Periodo,Usuarios,Consumo,ISO
0,1,01,001,Aguascalientes,Aguascalientes,01,2010,231727.0,281228528.0,MX-AGU
1,1,01,001,Aguascalientes,Aguascalientes,1A,2010,0.0,0.0,MX-AGU
2,1,01,001,Aguascalientes,Aguascalientes,1B,2010,0.0,0.0,MX-AGU
3,1,01,001,Aguascalientes,Aguascalientes,1C,2010,0.0,0.0,MX-AGU
4,1,01,001,Aguascalientes,Aguascalientes,1D,2010,0.0,0.0,MX-AGU

In [31]:
usuarios_consumo_df.to_csv("data/Usuariosyconsumodeelectricidadpormunicipio_clean.csv", index=False)